language: python
jobs:
  include:
  - name: Python 3.6 on Ubuntu 18.04 (Bionic Beaver)
    dist: bionic
    python: 3.6
    before_install:
    - python --version
    - pip install -U pip
    - pip install coverage
    - pip install coveralls
    - pip install -r docs/requirements.txt
    - echo "${USER}:12345678" | sudo chpasswd
  - name: Python 3.7 on Ubuntu 18.04 (Bionic Beaver)
    dist: bionic
    python: 3.7
    before_install:
    - python --version
    - pip install -U pip
    - pip install coverage
    - pip install coveralls
    - pip install -r docs/requirements.txt
    - echo "${USER}:12345678" | sudo chpasswd
  - name: Python 3.8 on Ubuntu 18.04 (Bionic Beaver)
    dist: bionic
    python: 3.8
    before_install:
    - python --version
    - pip install -U pip
    - pip install coverage
    - pip install coveralls
    - pip install -r docs/requirements.txt
    - echo "${USER}:12345678" | sudo chpasswd
install:
- pip3 install .
script: coverage run -m unittest discover
after_success:
- coveralls
deploy:
  provider: pypi
  username: __token__
  password:
    secure: Rr+7b047N51JC7X6xIioDAsrBrS3IQC5zHGLizPsG8CyxHOUPevveKXAhz9TAbao2+4ZnrnE1iLOWfEmf+dIJHpJ8MkAeO94XJgHlaP48upbsb2jZParwWvzZDUzU86JOAb7vYeeBl4/nqAlP0Y6ywJeuuKi3n5ADqCXFS3u4r45LykZPOE8XNWgIRFDf4Cev1PXXir+ixC61ajKD+3xpNWa83uxLfdThmYdtlcdxSsVwg3b0zKirmTzQtkSU2xZHzg9qcJX0+s7SQQ2v7Uo8bG7ca9u0BZfhU6ylI3oevWeA3s4nqzViZ9wNRyaEnHG5CS8jWakqWHUVDH4x8zX+jY5OM4h2ivEdOXrEGLYW3V0Etx151+9hBSKxWAm2XI9Mi013WjszzXk6hvRGj6r6yvhj186TVZvswZ6wdG0fZmDgKBeWqgZcPuJ2BqODj/3p0kp1PHQegyBBG/UBoJb0MTRtxkQUVVMtr8HmOGg09PXOHvIZAMtbPIkfA5JyqcmTCo1hPnnDD4hI63CgFWgt/QY02fVYBFuPuZwYOMjZJf1dw5xzvLRXN9zRsr97/GW5m8nCUNksadDBy8NRmoq/TrjEg5veifgI/BfdcUwp+Dp/uovxMaMhsmkjPlJW26KnMFycg8CRNRU2gOH+ZSw5/BLHu1C2fm6orJEW0lq/jI=
  skip_existrung: true
