language: python
jobs:
  include:
    # ===== Linux ======
    - name: "Python 3.6 on Ubuntu 18.04 (Bionic Beaver)"
      dist: bionic
      python: 3.6
      before_install:
      - python --version
      - pip install -U pip
      - pip install coverage
      - pip install coveralls
      - pip install -r docs/requirements.txt
      - echo '$USER:12345678' | sudo chpasswd
    - name: "Python 3.7 on Ubuntu 18.04 (Bionic Beaver)"
      dist: bionic
      python: 3.7
      before_install:
      - python --version
      - pip install -U pip
      - pip install coverage
      - pip install coveralls
      - pip install -r docs/requirements.txt
      - echo '$USER:12345678' | sudo chpasswd
    - name: "Python 3.8 on Ubuntu 18.04 (Bionic Beaver)"
      dist: bionic
      python: 3.8
      before_install:
      - python --version
      - pip install -U pip
      - pip install coverage
      - pip install coveralls
      - pip install -r docs/requirements.txt
      - echo '$USER:12345678' | sudo chpasswd
install:
  - pip3 install .
script: coverage run -m unittest discover
after_success:
  - coveralls # submit coverage